version: '2'
services:
  app:
    build:
      context: .
    depends_on:
      - db
    links:
      - db
    environment:
      - HOME_CHANNEL=meta
      - SLACK_TOKEN=xoxb-75093562244-aZ7IW3oObsGQOioZdBO5bEMo
      - DATABASE_URL=postgres://postgres:auniquepasswordnoonewillguess123@db/nom_db
      - WEB_DOMAIN=79545594.ngrok.io
      - PORT=8000
    volumes:
      - ./tech404logs:/usr/src/app/tech404logs
    ports:
      - 8000:8000
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_PASSWORD=auniquepasswordnoonewillguess123
      - POSTGRES_DB=nom_db
